[package]
name = "stock_stalker"
version = "0.1.0"
edition = "2024"

[features]
default = ["random"]
random = ["dep:rand"]

[dependencies]
rand = {version = "0.10", optional = true}
clap = {version = "4.6", features = ["derive"]}
once_cell = "1.21"

[lib]
path = "src/lib.rs"

[[bin]]
name = "quote_streamer"
path = "bins/quote_streamer/main.rs"

[[bin]]
name = "subscriber"
path = "bins/subscriber/main.rs"